# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color

# Window manager
window:
  padding:
    x: 10
    y: 10

  dimensions:
    columns: 80
    lines: 30

# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Extra Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 15

# Colors (Night Owl)
colors:
  # Default colors
  primary:
    background: "#011627"
    foreground: "#d6deeb"

  cursor:
    text: "#011627"
    cursor: "#7e57c2"

  selection:
    text: "#000000"
    background: "#ffffff"

    # Normal colors
  normal:
    black: "#011627"
    red: "#ef5350"
    green: "#22da6e"
    yellow: "#c5e478"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#21c7a8"
    white: "#ffffff"

    # Bright colors
  bright:
    black: "#575656"
    red: "#ef5350"
    green: "#22da6e"
    yellow: "#ffeb95"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#7fdbca"
    white: "#ffffff"

  # Search colors
  search:
    bar:
      background: "#011627"
      foreground: "#21c7a8"

# Cursor style
cursor:
  style:
    # Cursor shape
    # ▇ Block or _ Underline or | Beam
    shape: Beam

# Shell
shell:
  program: /bin/zsh
  args:
    - --login

# Key bindings
key_bindings:
  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Control, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: PageUp, mods: Shift, mode: ~Alt, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, mode: ~Alt, action: ScrollPageDown }
  - { key: Home, mods: Shift, mode: ~Alt, action: ScrollToTop }
  - { key: End, mods: Shift, mode: ~Alt, action: ScrollToBottom }
  # Search Mode
  - { key: Return, mode: Search|Vi, action: SearchConfirm }
  - { key: Escape, mode: Search, action: SearchCancel }
  - { key: C, mods: Control, mode: Search, action: SearchCancel }
  - { key: U, mods: Control, mode: Search, action: SearchClear }
  - { key: W, mods: Control, mode: Search, action: SearchDeleteWord }
  - { key: P, mods: Control, mode: Search, action: SearchHistoryPrevious }
  - { key: N, mods: Control, mode: Search, action: SearchHistoryNext }
  - { key: Up, mode: Search, action: SearchHistoryPrevious }
  - { key: Down, mode: Search, action: SearchHistoryNext }
  - { key: Return, mode: Search|~Vi, action: SearchFocusNext }
  - { key: Return, mods: Shift, mode: Search|~Vi, action: SearchFocusPrevious }
  # (Windows, Linux, and BSD only)
  - { key: V, mods: Control|Shift, mode: ~Vi, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: F, mods: Control|Shift, mode: ~Search, action: SearchForward }
  - { key: B, mods: Control|Shift, mode: ~Search, action: SearchBackward }
  - { key: C, mods: Control|Shift, mode: Vi|~Search, action: ClearSelection }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
